### ISSUE TITLE
Create AWS Lambda function that takes a multi-page PDF, splits it into single pages and upload to S3

### ISSUE THREAD

**Issue by gonzaloaune** [stakwork/stak-bounties#6]
**Objective**
Being able to split a multi-page PDF into multiple single page PDF's and upload the results to S3.

**The Task**
We need an AWS Lambda function that based on an SQS message, it splits a PDF file per page and uploads each separate PDF the  to S3 (location is specified in the SQS message) and send back the URL’s of the uploaded pages via another queue specified in the original SQS message.

Sample original SQS message:

```json
{
    "file_url": "path_to_multi_page_pdf",
    "bucket": "s3_bucket",
    "store_dir": "s3_bucket_path",
    "results_queue": "sqs_queue_name_to_post_results"
}
```

example:

```json
{
    "file_url": "http://file_example.com/multi-page.pdf",
    "bucket": "bounties",
    "store_dir": "/directory/pdfs/",
    "results_queue": "pdf-results-sqs-queue"
}
```

The Lambda function should post the following JSON to the pdf-results-sqs-queue queue:

```json
{
    "results": [
        {
            "url": "page-1.pdf",
            "page": 1
        },
        {
            "url": "page-2.pdf",
            "page": 2
        }
    ]
}
```

**Delieverables**

- [x] Functional AWS Lambda package (with dependencies included if any)
- [x] Can be done in python, node, ruby or a dockerised version of them.

**Comment by aliraza556** [comment]
Hi @gonzaloaune could you assign me this task?

**Comment by gonzaloaune** [comment]
Done @aliraza556

**Comment by aliraza556** [comment]
Hi @gonzaloaune,

1- **Direct S3 Interaction Approach:**  This method involves setting up the Lambda function to automatically trigger when a multi-page PDF is placed in a specific S3 bucket. The Lambda function will then retrieve this PDF, split it into individual pages, and upload each page as a separate PDF back to a specified directory in the S3 bucket. This approach is highly efficient for workflows where the PDFs are already stored or will be stored in S3. It minimizes the need for additional steps or external API calls.

2- **API Gateway Approach:** Alternatively, we can set up an API Gateway that accepts uploads of multi-page PDFs. Once a PDF is uploaded through this API, the Lambda function will be triggered to process the file - splitting it into individual pages and then uploading these to the specified S3 bucket path. This method is beneficial if you need a more flexible solution where PDFs can be uploaded directly from different sources, not limited to those already in S3.

Please let me know which approach we should adopt?

**Comment by aliraza556** [comment]
Hi @gonzaloaune,
Please review the PR #7.  Please provide me with your feedback.

**Comment by aliraza556** [comment]
Hi @gonzaloaune,
This bounty is available?
https://community.sphinx.chat/bounty/482

**Comment by gonzaloaune** [comment]
> Hi @gonzaloaune, Please review the PR #7. Please provide me with your feedback.

Thanks @aliraza556, will take a look now and get back to you.

> Hi @gonzaloaune, This bounty is available? https://community.sphinx.chat/bounty/482

Sorry that one is not available anymore, Marvel completed it long time ago I forgot to mark it as paid.

**Comment by gonzaloaune** [comment]
Thanks @aliraza556, it works as expected.
