### ISSUE TITLE
Extract EXIF data from image

### ISSUE THREAD

**Issue by Edvardoh** [stakwork/stak-bounties#8]
**Opportunity**
Customers need to extract EXIF and other metadata available in image uploads, including but not limited to:

- image_format = jpg, jpeg, png, svg, tiff, heic
- size = '3MB',
- resolution = '3000x2000',
- gps= {'latitude': 37.8199, 'longitude': -122.4783},
- original_filename = 'golden_gate_sunset.jpg',

**Resources**
Example Image with EXIF data including GPS https://github.com/ianare/exif-samples/blob/master/jpg/gps/DSCN0010.jpg
- more examples can be found in this [Github repo](https://github.com/ianare/exif-samples) to test the solution

Web based EXIF extraction example tool for reference: https://jimpl.com/results/74kBfHEqunePiA2zbrtoBR1T?target=exif

**Deliverables**
- [ ] Dockerized app that can be deployed in a Lambda function (Python, Ruby, or Javascript preferred) with all necessary dependencies specified in the docker file
- [ ] Specifications to run the Dockerized app in a Lambda function - Ram needed, disk space needed, etc. Can be a video explanation or step-by-step instructions.

**Acceptance Criteria**
- [ ] Accepts an image url, .jpg/.jpeg, .png, .svg, .tiff, .heic
- [ ] Returns all EXIF data available as a JSON object with key:value pairs, including the original image url, and including null states ie `"gps": null` or `"gps": {"latitude": 37.8199, "longitude": -122.4783}`
- [ ] Returns an error if the image could not be processed or is otherwise corrupt, with a descriptive failure reason.

**Comment by Fog3211** [comment]
@pitoi i want to try

**Comment by ColdMice** [comment]
@Edvardoh I wish to contribute towards this

**Comment by hkarani** [comment]
@Edvardoh I have a solution.

**Comment by Edvardoh** [comment]
Thanks for your responses @Fog3211 @ColdMice I'm sorry I couldn't respond back in time for you to try, but we will be posting more bounties so keep an eye out.

@hkarani can you link a Pull Request if you have a solution @gonzaloaune can review your code, also include config/specs for suggested Ram and Disk Space needed to deploy to a Lambda function.

If you can share your pubkey I can assign you the issue on bounties, I couldn't find you in the search results: https://community.sphinx.chat/bounty/1348

**Comment by Edvardoh** [comment]
@hkarani if you don't already have Sphinx you can follow this guide to download so we can assign it to you and you can try other bounties as well https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing

**Comment by hkarani** [comment]
I'm submitting the pull requests with the explainers and code in few.

**Comment by hkarani** [comment]
Here is [link](https://github.com/hkarani/exif_extractor) with the code and readme with instructions.

**Comment by Edvardoh** [comment]
Thanks @hkarani I was able to download, run, and test it.

I had to change the test image path in test_run.py by removing the `/` to find the image, which is not a problem, just FYI.

The response however did not contain all the information, including GPS coordinates and filename both of which are available when I test the same .jpg image here: https://jimpl.com/results/3x735ztzMjJeW2azz8Rmfz5z?target=exif

Test response I got:
```
{'statusCode': 200, 'body': '{"filename": "", "fileformat": "JPEG", "imagesize": "(640, 480)", "bitspersample": "Null", "datetimeoriginal": "Null", "exposuretime": "Null", "isanimated": false, "imageheight": 480, "imagewidth": 640, "xresolution": "300.0", "yresolution": "300.0", "model": "COOLPIX P6000", "make": "NIKON", "datecreated": "2008:11:01 21:15:07", "flash": "Null", "orientation": 1, "imagedescription": "                               ", "ycbcrsubsampling": "Null", "software": "Nikon Transfer 1.1 W", "gps": {"gpslatituderef": "Null", "gpslatitude": "Null", "gpslongituderef": "Null", "gpslongitude": "Null"}}', 'headers': {'Content-Type': 'application/json'}}
```

Can you check to see why this data is not available in the response plz?

**Comment by hkarani** [comment]
Okay I can polish the code, though some images can be scrapped to remove
exif data. It is mostly done by some social media apps.

**Comment by ecurrencyhodler** [comment]
@Edvardoh hkarani is asterisk32 on sphinx. Can you assign the bounty to him?

**Comment by hkarani** [comment]
{'statusCode': 200, 'body': '{"ImageDetails": {"Filename": "DSCN0010.jpg", "Image Size": [640, 480], "Image Height": 480, "Image Width": 640, "Image Format": "JPEG", "Image Mode": "RGB", "Image is Animated": false, "Frames in Image": 1}, "ExifData": {"ExifVersion": "b\'0220\'", "ComponentsConfiguration": "b\'\\\\x01\\\\x02\\\\x03\\\\x00\'", "FlashPixVersion": "b\'0100\'", "DateTimeOriginal": "2008:10:22 16:28:39", "DateTimeDigitized": "2008:10:22 16:28:39", "ExposureBiasValue": "0.0", "MaxApertureValue": "2.9", "MeteringMode": "5", "LightSource": "0", "Flash": "16", "FocalLength": "24.0", "UserComment": "b\'ASCII\\\\x00\\\\x00\\\\x00                                                                                                                     \\\\x00\'", "ColorSpace": "1", "ExifImageWidth": "640", "ExifInteroperabilityOffset": "896", "SceneCaptureType": "0", "ExifImageHeight": "480", "Contrast": "0", "Saturation": "0", "Sharpness": "0", "SubjectDistanceRange": "0", "FileSource": "b\'\\\\x03\'", "ExposureTime": "0.013333333333333334", "FNumber": "5.9", "SceneType": "b\'\\\\x01\'", "ExposureProgram": "2", "CustomRendered": "0", "ISOSpeedRatings": "64", "ExposureMode": "0", "WhiteBalance": "0", "DigitalZoomRatio": "0.0", "FocalLengthIn35mmFilm": "112", "GainControl": "0"}, "GPSInfo": {"GPSLatitudeRef": "N", "GPSLatitude": "(43.0, 28.0, 2.814)", "GPSLongitudeRef": "E", "GPSLongitude": "(11.0, 53.0, 6.45599999)", "GPSAltitudeRef": "b\'\\\\x00\'", "GPSTimeStamp": "(14.0, 27.0, 7.24)", "GPSSatellites": "06", "GPSImgDirectionRef": "\\u0000", "GPSMapDatum": "WGS-84   ", "GPSDateStamp": "2008:10:23"}, "InteropData": {"InteropIndex": "R98", "2": "b\'0100\'"}, "IFD1Data": {"JpegIFOffset": "4548", "JpegIFByteCount": "6702", "Compression": "6", "ResolutionUnit": "2", "XResolution": "72.0", "YResolution": "72.0"}}', 'headers': {'Content-Type': 'application/json'}}

**Comment by hkarani** [comment]
@Edvardoh  right now it can return more detailed data. I hope that helps.

**Comment by Edvardoh** [comment]
Thanks @hkarani - perfect

@VoxStellarum will review your PR and once approved we'll get you paid

**Comment by hkarani** [comment]
Sounds great, thanks for the update. @Edvardoh I'm having issues chatting with you on Sphinx (FAILURE_REASON_NO_ROUTE).

**Comment by VoxStellarum** [comment]
@hkarani 

I am testing the dockerized app and it throws an error for some of the images provided here [Github repo](https://github.com/ianare/exif-samples)

List of examples I tested:

- Crémieux11.tiff
- DSCN0010.jpg
- Jobagent.tiff

```python
{'errorMessage': '<IFD.Makernote: 37500>', 'errorType': 'KeyError', 'requestId': 'b939948c-0790-4299-b863-cdc969f6b782', 'stackTrace': ['  File "/var/task/lambda_function.py", line 19, in handler\n    makernote_ifd = exif_data.get_ifd(ExifTags.IFD.Makernote)\n', '  File "/var/lang/lib/python3.12/site-packages/PIL/Image.py", line 3812, in get_ifd\n    tag_data = self._ifds[ExifTags.IFD.Exif][tag]\n']}
```

**Comment by hkarani** [comment]
I'm handling that, but equally the Makernote info can be obtained from Exifdata. Fixing that right away..and running test runs on those other images.

**Comment by hkarani** [comment]
UPDATE:

I've been researching for a better solution based on the library behind https://jimpl.com/results/3x735ztzMjJeW2azz8Rmfz5z?target=exif. I've ported the solution to JavaScript(for farmiliarity) as opposed to Python. I'm working on how to deploy a Node library to AWS Lambda ; deploying the code throws import errors.

**Comment by Edvardoh** [comment]
Thx for the update @hkarani - let us know when this is ready to test again

**Comment by hkarani** [comment]
@VoxStellarum  and @Edvardoh 
I have the working code here https://github.com/hkarani/exif_extractor_js

You can use the code and docs here https://github.com/hkarani/exif_extractor_js_tests to make the Lambda function invocations locally and in deployment.

If need anything let me know

**Comment by gonzaloaune** [comment]
Hey @hkarani, I was reviewing your latest code but I found some issues:

1) Input should be just a URL, not a filename + a base64 encoded string of an image, that should be done within the app, we are just going to provide a URL of an image, or it could not be an image and it should be handled gracefully in that case if there's an error.

2) Output should be a JSON with the original URL and the exif data as per the original request

**Comment by hkarani** [comment]
Hey @gonzaloaune, no problem. I can do that.

**Comment by hkarani** [comment]
@Edvardoh I pushed the changes to work with image urls. It also works when deployed to AWS Lambda.

The lambda code is here https://github.com/hkarani/exif_extractor_js

And you can use the various tests put here https://github.com/hkarani/exif_extractor_js_tests
 

A sample output looks like this 

{
  SourceFile: 'https://github.com/ianare/exif-samples/raw/master/tiff/Cr%C3%A9mieux11.tiff',
  errors: [],
  Orientation: 1,
  ExifToolVersion: 12.76,
  FileName: 'file.dat',
  Directory: '/tmp',
  FileSize: '11 kB',
  FileModifyDate: {
    _ctor: 'ExifDateTime',
    year: 2024,
    month: 2,
    day: 18,
    hour: 14,
    minute: 43,
    second: 52,
    tzoffsetMinutes: 0,
    rawValue: '2024:02:18 14:43:52+00:00',
    zoneName: 'UTC',
    inferredZone: false
  },
  FileAccessDate: {
    _ctor: 'ExifDateTime',
    year: 2024,
    month: 2,
    day: 18,
    hour: 14,
    minute: 43,
    second: 52,
    tzoffsetMinutes: 0,
    rawValue: '2024:02:18 14:43:52+00:00',
    zoneName: 'UTC',
    inferredZone: false
  },
  FileInodeChangeDate: {
    _ctor: 'ExifDateTime',
    year: 2024,
    month: 2,
    day: 18,
    hour: 14,
    minute: 43,
    second: 52,
    tzoffsetMinutes: 0,
    rawValue: '2024:02:18 14:43:52+00:00',
    zoneName: 'UTC',
    inferredZone: false
  },
  FilePermissions: '-rw-rw-r--',
  FileType: 'TIFF',
  FileTypeExtension: 'tif',
  MIMEType: 'image/tiff',
  ExifByteOrder: 'Big-endian (Motorola, MM)',
  ImageWidth: 199,
  ImageHeight: 47,
  BitsPerSample: '8 8 8 8',
  Compression: 'LZW',
  PhotometricInterpretation: 'RGB',
  StripOffsets: 8,
  SamplesPerPixel: 4,
  RowsPerStrip: 47,
  StripByteCounts: 6205,
  XResolution: 72,
  YResolution: 72,
  PlanarConfiguration: 'Chunky',
  ResolutionUnit: 'inches',
  Software: 'Mac OS X 10.5.8 (9L31a)',
  ModifyDate: {
    _ctor: 'ExifDateTime',
    year: 2012,
    month: 1,
    day: 9,
    hour: 22,
    minute: 52,
    second: 11,
    rawValue: '2012:01:09 22:52:11',
    inferredZone: false
  },
  Artist: 'Jean Cornillon',
  Predictor: 'Horizontal differencing',
  ExtraSamples: 'Associated Alpha',
  SampleFormat: 'Unsigned; Unsigned; Unsigned; Unsigned',
  ProfileCMMType: 'Apple Computer Inc.',
  ProfileVersion: '2.0.0',
  ProfileClass: 'Display Device Profile',
  ColorSpaceData: 'RGB ',
  ProfileConnectionSpace: 'XYZ ',
  ProfileDateTime: {
    _ctor: 'ExifDateTime',
    year: 2012,
    month: 1,
    day: 4,
    hour: 6,
    minute: 8,
    second: 30,
    rawValue: '2012:01:04 06:08:30',
    inferredZone: false
  },
  ProfileFileSignature: 'acsp',
  PrimaryPlatform: 'Apple Computer Inc.',
  CMMFlags: 'Not Embedded, Independent',
  DeviceManufacturer: '',
  DeviceModel: '',
  DeviceAttributes: 'Reflective, Glossy, Positive, Color',
  RenderingIntent: 'Perceptual',
  ConnectionSpaceIlluminant: '0.9642 1 0.82491',
  ProfileCreator: 'Apple Computer Inc.',
  ProfileID: '26fa5c4d4e9e4f577c8d8fdd3077f199',
  RedMatrixColumn: '0.35736 0.20616 0.02617',
  GreenMatrixColumn: '0.45222 0.70026 0.12091',
  BlueMatrixColumn: '0.1546 0.09399 0.6777',
  MediaWhitePoint: '0.95047 1 1.0891',
  ChromaticAdaptation: '1.04788 0.02292 -0.0502 0.02957 0.99049 -0.01706 -0.00923 0.01508 0.75165',
  RedTRC: {
    _ctor: 'BinaryField',
    bytes: 14,
    rawValue: '(Binary data 14 bytes, use -b option to extract)'
  },
  GreenTRC: {
    _ctor: 'BinaryField',
    bytes: 14,
    rawValue: '(Binary data 14 bytes, use -b option to extract)'
  },
  BlueTRC: {
    _ctor: 'BinaryField',
    bytes: 14,
    rawValue: '(Binary data 14 bytes, use -b option to extract)'
  },
  VideoCardGamma: {
    _ctor: 'BinaryField',
    bytes: 1554,
    rawValue: '(Binary data 1554 bytes, use -b option to extract)'
  },
  NativeDisplayInfo: {
    _ctor: 'BinaryField',
    bytes: 1598,
    rawValue: '(Binary data 1598 bytes, use -b option to extract)'
  },
  ProfileDescription: 'Color LCD',
  'ProfileDescriptionML-nb-NO': 'Farge-LCD',
  'ProfileDescriptionML-pt-PT': 'LCD a Cores',
  'ProfileDescriptionML-sv-SE': 'Färg-LCD',
  'ProfileDescriptionML-fi-FI': 'Väri-LCD',
  'ProfileDescriptionML-da-DK': 'LCD-farveskærm',
  'ProfileDescriptionML-zh-CN': '彩色 LCD',
  'ProfileDescriptionML-fr-FR': 'Écran LCD',
  'ProfileDescriptionML-ja-JP': 'カラー LCD',
  ProfileDescriptionML: 'Color LCD',
  'ProfileDescriptionML-pl-PL': 'Kolor LCD',
  'ProfileDescriptionML-pt-BR': 'LCD Colorido',
  'ProfileDescriptionML-es-ES': 'LCD color',
  'ProfileDescriptionML-zh-TW': '彩色液晶顯示器',
  'ProfileDescriptionML-ru-RU': 'Цветной ЖК-дисплей',
  'ProfileDescriptionML-ko-KR': '컬러 LCD',
  'ProfileDescriptionML-de-DE': 'Farb-LCD',
  'ProfileDescriptionML-nl-NL': 'Kleuren-LCD',
  'ProfileDescriptionML-it-IT': 'LCD colori',
  MakeAndModel: {
    _ctor: 'BinaryField',
    bytes: 40,
    rawValue: '(Binary data 40 bytes, use -b option to extract)'
  },
  ProfileCopyright: 'Copyright Apple, Inc., 2012',
  ImageSize: '199x47',
  Megapixels: 0.009,
  warnings: []
}

**Comment by gonzaloaune** [comment]
This works as expected now @hkarani @Edvardoh

**Comment by Edvardoh** [comment]
Just closed and paid the bounty, nice one @hkarani

**Comment by hkarani** [comment]
Glad to be of use to you. I really enjoyed working on the problem.
