### ISSUE TITLE
Unzip a file from s3 and save contents into a new folder, returning a list of file urls

### ISSUE THREAD

**Issue by Edvardoh** [stakwork/stak-bounties#9]
We need a Lambda function which takes a .zip file that has already been uploaded to an s3 bucket, unzips the file, and saves the contents into a new subfolder in the bucket.

The subfolder should share the name of the original zip, and the contained files in the zip should preserve their paths/filenames relative to the original zip. With the exception of any strange characters such as `~ ñ é`, to create a friendly URL.

When finished, the function should return a list of urls for all the files that were saved successfully, and a list of filenames that were not saved successfully (if any)

Sample input .zip:
[test_batch1.zip](https://github.com/stakwork/stak-bounties/files/14142805/test_batch1.zip)

**Deliverables**
- [ ] A dockerized app which takes a url to a .zip file in an s3 bucket, unzips and saves the contents into a new subfolder in the same bucket, and outputs a list of successfully saved file urls
- [ ] Instructions to configure the bucket - RAM  and disk space needed, s3 configuration, etc.

**Acceptance Criteria**
- [ ] It should accept a public-view s3 url to a .zip file as input
- [ ] If subfolders inside the .zip folder, it should recursively create the same subfolder structure in the s3 bucket
- [ ] It should output a list of successfully saved files' s3 urls
- [ ] It should output a list of failed file names
- [ ] original file names should be preserved - with the exception of any special characters, which should be removed to create friendly urls
- [ ] do not compress or downsample the original files, preserve as much of the original file data as possible
- [ ] Returns a descriptive error if the function fails - ie. memory exceeded, etc.

**Comment by aliraza556** [comment]
@Edvardoh,
Could you assign this to me? I have worked on almost related [issues](https://github.com/stakwork/stak-bounties/issues/6).

**Comment by aliraza556** [comment]
@Edvardoh,
Thanks Man!

**Comment by Edvardoh** [comment]
@aliraza556 thanks for the fast response! Assigned to you, please link the PR when ready. Do you have a Sphinx pubkey so I can assign the bounty to you as well? https://community.sphinx.chat/bounty/1384

**Comment by aliraza556** [comment]
Yes,
My Name Ali Raza in Sphinx `03b255bc52ad917a9eb5b19c9cb58211458f2129d1c4aca1c7fc29cc5cf74e8b7e:03a6ea2d9ead2120b12bd66292bb4a302c756983dc45dcb2b364b461c66fd53bcb:1099521589249`

**Comment by aliraza556** [comment]
Hi @Edvardoh,
Please see the [demo](https://www.loom.com/share/e7178de2c75940cd9b0b3eeebd1f29f4). If everything is fine, I will make a PR once I have created a dockerized file.

**Comment by aliraza556** [comment]
Hi @Edvardoh,
Please review the PR #10.

**Comment by aliraza556** [comment]
Hi @Edvardoh 
Are you available? Could you please review my [PR](https://github.com/stakwork/stak-bounties/pull/10)?

**Comment by Edvardoh** [comment]
Hi @aliraza556 I just watched the demo - and looks great, thanks for sharing the video!

@VoxStellarum will review your PR and once confirmed we'll get you paid.

Thx!

**Comment by aliraza556** [comment]
Hi @Edvardoh,
Please mark the bounty as paid when you are free. Marking the bounty as paid is essential for me to be eligible for the next bounty assignment. Thank you!

**Comment by Edvardoh** [comment]
Thank you @aliraza556 Gonza confirmed this is working well, I'll pay out the bounty and close this out :)

**Comment by Edvardoh** [comment]
@aliraza556 paid
